name: flutterflip
description: A Reversi game built in Flutter.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  async: ^2.8.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf
        - asset: assets/fonts/Roboto-ThinItalic.ttf
          style: italic








